### ISSUE TITLE
Drag 'n drop issue when return from fullscreen

### ISSUE THREAD

**Issue by walkero-gr** [AmigaPorts/SDL#12]
I have an issue which existed on 2.0.14 releases and it still happens with 2.0.20.

The editor that I port when I start it, it opens in window mode and I can drag 'n drop files in it and they open just fine.

But if I change it to Fullscreen with the following method
SDL_SetWindowFullscreen(window, SDL_WINDOW_FULLSCREEN_DESKTOP);

and then back again with
SDL_SetWindowFullscreen(window, 0);
to return to window mode.
After that drag 'n drop is disabled and the X cursor appears when I try to drop a file in the window.

The same code on other systems is working fine.

**Comment by capehill** [comment]
Does RC5 fix this problem? https://github.com/AmigaPorts/SDL-2.0/releases/tag/v2.0.20-rc5-amigaos4

**Comment by walkero-gr** [comment]
This seems to work fine on RC5. Thank you for fixing it.
