### ISSUE TITLE
SDL2/SDL_GetWindowWMInfo() always returns 0

### ISSUE THREAD

**Issue by javierdlr** [AmigaPorts/SDL#128]
[SDL2syswm_c.txt](https://github.com/user-attachments/files/17001503/SDL2syswm_c.txt)

compiling above example on AmigaOS4 I always get 0, under macOS returns 1.

Is such funcion implemented? IIRC in SDL1 there is SDL_GetWMInfo() and works fine.

**Comment by capehill** [comment]
https://wiki.libsdl.org/SDL2/SDL_GetWindowWMInfo

It seems that version information was not set correctly.

SDL_GetError() usually gives some extra information and there is also a serial debug version of the library.

**Comment by javierdlr** [comment]
adding SDL_VERSION(&wmInfo.version) make code working. THXaLOT
