### ISSUE TITLE
CPU usage increase when lose focus

### ISSUE THREAD

**Issue by walkero-gr** [AmigaPorts/SDL#13]
I think there is a bug in 2.0.20 releases where when the SDL window loses the focus, the CPU usage increases 2-3% every second. As soon as the user clicks on the window and it gets the focus, then the CPU goes to 0-1% and remains there if the user does not do anything. If the focus is lost, again, the CPU usage increase.

I tried 2.0.14upd1 release and compiled my app with that and I couldn't reproduce it. 
Then I installed again 2.0.20rc1 release, compiled my app again, and the issue comes back.
I tried 2.0.14upd1 release for a second time, compiled my app and I couldn't reproduce it.

Hope my description helps you find the issue.

**Comment by capehill** [comment]
I wasn't able to reproduce issue with a simple window test. I'm using CPUWatcher tool to check the load.

1) before starting, load is at 1%.
2) after SDL2 app is started, load increases to 2%
3) after window focus is lost, load is still at 2%
4) when quitting, load drops back to 1%

It could be some application-specific issue? Do you see anything on serial?

**Comment by walkero-gr** [comment]
Haven't checked the serial, but I can do it. What should I expect to see there?

**Comment by capehill** [comment]
Ideally nothing, unless you are running debug builds. I'm just looking for explanation for increased CPU usage.

What application is doing in its "focus lost" state?

Is it using SDL_PollEvent or SDL_WaitEvent?

Upstream has changed SDL_WaitEvent after 2.0.14 according to [WhatsNew](https://github.com/AmigaPorts/SDL-2.0/blob/main/WhatsNew.txt)

**Comment by walkero-gr** [comment]
I checked the serial and I get nothing there.

It is using SDL_WaitEvent (https://github.com/lite-xl/lite-xl/blob/master/src/api/system.c#L286-L295) which is triggered at https://github.com/lite-xl/lite-xl/blob/master/data/core/init.lua#L1607-L1615

**Comment by capehill** [comment]
Thanks. I will create a small test case for SDL_WaitEvent: hopefully it could reveal something.

**Comment by walkero-gr** [comment]
Thank you so much for your work on SDL

**Comment by capehill** [comment]
Reproduced issue using SDL_WaitEvent. SDL seems to generate new events of type SDL_POLLSENTINEL and queue keeps growing if there are no other events. When queue grows, handling takes more CPU time so this probably explains why CPU usage starts to increase linearly.

I'm not sure yet how to deal with this properly: need to check behaviour on Linux as well. 

It seems that there is a workaround: you can temporarily try "setenv SDL_POLL_SENTINEL 0" and situation should get back to normal. https://github.com/libsdl-org/SDL/blob/main/include/SDL_hints.h#L1007

**Comment by capehill** [comment]
Does RC5 fix this problem for you? https://github.com/AmigaPorts/SDL-2.0/releases/tag/v2.0.20-rc5-amigaos4

**Comment by walkero-gr** [comment]
This seems to work fine on RC5. Thank you for fixing it.
