### ISSUE TITLE
Add locale support for prefs program

### ISSUE THREAD

**Issue by capehill** [AmigaPorts/SDL#15]
Originally reported here https://github.com/AmigaPorts/SDL/issues/196

**Comment by samo790** [comment]
Fixed by Javier :-)

**Comment by samo790** [comment]
Any news on this one?
This ticket (and ticket #28) seems practically already implemented, they should be easy to merge on main (?)

**Comment by capehill** [comment]
This should be now merged and waiting for next release. Thanks for all contributions.
