### ISSUE TITLE
SDL locked audio issue

### ISSUE THREAD

**Issue by samo79** [AmigaPorts/SDL#21]
If you have an AHI output busy with another application opened (lets say for example MPlayer) and you launch an SDL app that still use the same audio source --> we got this message error: 

Could not initialize SDL: Failed to load AHI

Raziel added:
SDL doesn't like another program hogging AHI resources...i got that with other SDL apps too.

https://www.amigans.net/modules/newbb/viewtopic.php?post_id=130403#forumpost130403

**Comment by raziel-** [comment]
While I don't know anything about SDL's AHI handling and I also don't think it's SDL's responsibility to work around other programs erroneous handling of AHI resources, it *might* be an idea for SDL to check for locked AHI resources and, if found, simply use one of the free units available instead (Music, 0 to 3)?

If such is even possible...

**Comment by capehill** [comment]
This doesn't seem to be an SDL issue. If some application uses low-level (function) API to control AHI, then other applications cannot use it. For example, in such a case, try playing test sound using AHI prefs (any unit).

AFAIK the only way is to change MPlayer to use device API.
