### ISSUE TITLE
Add system versioning to test files

### ISSUE THREAD

**Issue by samo790** [AmigaPorts/SDL#27]
It may be convenient to add a versioning to all the test programs:

controllermap
sdl2benchmark
testgamecontroller
testjoystick
testver

**Comment by capehill** [comment]
Personally I don't see the point in adding $VER to random SDL test programs. It's best to keep generic changes in minimum to make upstream comparison easier.

I will consider it for sdl2benchmark because versions can be important in benchmark comparisons.
