### ISSUE TITLE
Update to README-amigaos4.md

### ISSUE THREAD

**Issue by samo790** [AmigaPorts/SDL#34]
The about joystick section in README-amigaos4.md need to be updated:

Speedlink Competition Pro
Ewent Joypad EW3170
PS2 Joystick (USB adaptor)
SHARK 91230 Joystick
MAGIC-NS
Wireless Controller
8Bitdo SN30 Pro
Thrustmaster dual analog 3.2
XEOX Gamepad SL-6556-BK
Strike2 Joystick
GeeekPi_A gamepad
Logitech Cordless RumblePad 2
Logitech RumblePad 2 USB
Logitech(R) Precision(TM) Gamepad
Logitech Dual Action
MAYFLASH Arcade Fightstick F300
Game Controller for Android
2In1 USB Joystick

**Comment by capehill** [comment]
Updated in 2.26.1 RC 2.
