### ISSUE TITLE
Improve installer for copy documentation files

### ISSUE THREAD

**Issue by samo790** [AmigaPorts/SDL#40]
The installer could be extended a bit in order to install also the documentation files into SYS:Documentation

**Comment by samo790** [comment]
Ok the readme file installs correctly in the documentation directory... :-)
However thing could be improved like this... the installer could create an "sdl2" directory into the documentation directory, and then copy both the readme file and the changelog file into it :-)

**Comment by capehill** [comment]
Now all documentation is copied to SYS:Documentation/SDL2/.

https://github.com/AmigaPorts/SDL/releases/tag/v2.30.0-rc2-amigaos4
