### ISSUE TITLE
New pad mapping (Playstation 2 alike pad)

### ISSUE THREAD

**Issue by samo790** [AmigaPorts/SDL#41]
This is a generic Playstation 2 alike controller (black, with USB Universal Serial Bus written in the middle)

See post: 
https://www.amigans.net/modules/newbb/viewtopic.php?post_id=140094#forumpost140094

205553422047616d6570616420202020,USB Gamepad,platform:AmigaOS
4,a:b2,b:b1,x:b3,y:b0,back:b8,start:b9,rightstick:b11,leftshoulder:b4,rightshoulder:b5,leftx:a0,lefty:a1,lefttrigger:b6,right
trigger:b7,

**Comment by capehill** [comment]
Added.
