### ISSUE TITLE
update SDL2 EW3710 SDL_gamepad_db.h AmigaOS4

### ISSUE THREAD

**Issue by javierdlr** [AmigaPorts/SDL#64]
Hi, I recalibrated the gamepad and this is the new/updated string/code (src/joystick/SDL_gamepad_db.h):

"0300000047656e657269632020205500,Ewent Joypad EW3170,platform:AmigaOS 4,a:b2,b:b1,x:b3,y:b0,back:b8,start:b9,leftstick:b10,rightstick:b11,leftshoulder:b4,rightshoulder:b5,dpup:h0.1,dpdown:h0.4,dpleft:h0.8,dpright:h0.2,-leftx:-a2,+leftx:+a0,lefty:a1,lefttrigger:b6,righttrigger:b7,",

BTW are the same "values" valid for AmigaOS4 SDL1? If yes you can update SDL1 gamepad as well.
TiA

**Comment by capehill** [comment]
SDL1 doesn't have these kind of mappings.

**Comment by javierdlr** [comment]
ok I just thought SDL1 had the gamecontroller database too. 
So only update SDL2 and done.
THX

**Comment by capehill** [comment]
GUID seems broken but mapping has been updated.
