### ISSUE TITLE
 Are the SDL_TEXTINPUT events suppressed with other keymaps than English?

### ISSUE THREAD

**Issue by walkero-gr** [AmigaPorts/SDL#73]
I am trying to make an SDL app of mine working when typing texts in other encodings than the English ones. For example, I want to type in Greek, but when I switch my locale the SDL_TEXTINPUT event is not triggered at all.

I have a small demo that shows the problem

```c


    #include <SDL.h>
    #include <stdio.h>
     
    int main(int argc, char* argv[]) {
        if (SDL_Init(SDL_INIT_VIDEO) < 0) {
            printf("SDL could not initialize! SDL_Error: %s\n", SDL_GetError());
            return 1;
        }
     
        SDL_Window* window = SDL_CreateWindow("SDL Unicode Example", SDL_WINDOWPOS_UNDEFINED, SDL_WINDOWPOS_UNDEFINED, 640, 480, SDL_WINDOW_SHOWN);
        if (window == NULL) {
            printf("Window could not be created! SDL_Error: %s\n", SDL_GetError());
            return 1;
        }
     
        SDL_Renderer* renderer = SDL_CreateRenderer(window, -1, SDL_RENDERER_ACCELERATED);
     
        SDL_Event e;
        int quit = 0;
     
        while (!quit) {
            while (SDL_PollEvent(&e) != 0) {
                if (e.type == SDL_QUIT) {
                    quit = 1;
                } else if (e.type == SDL_TEXTINPUT) {
                    // Handle Unicode characters
                    printf("Text input: %s\n", e.text.text);
                }
            }
        }
     
        SDL_DestroyRenderer(renderer);
        SDL_DestroyWindow(window);
        SDL_Quit();
     
        return 0;
    }
```
You can compile it with something like:
gcc -o sdl_textinput sdl_textinput.c -I/sdk/local/newlib/include/SDL2 -lSDL2

Does anyone know if that's the case and if there is a workaround? Is this something that is happening in our SDL port, or is it a problem of the keymap?

**Comment by capehill** [comment]
I think the problem is with raw key to utf-8 conversion. We are using MapRawKey function to convert to ANSI and then sending just the 7 lowest bits as "utf-8" to SDL2 core, so half of the ANSI characters are lost there.

Ideas welcome...

**Comment by walkero-gr** [comment]
@capehill Thank you for your reply. What would be the situation if we were sending all the bits of the characters? Since SDL applications are mostly working with their implementation and support of the unicode standard, they probably would continue to work fine, right? I guess the characters might not be visible correctly, but then a conversion of the character could be done using codesets or system functions.

**Comment by capehill** [comment]
@walkero-gr We were initially sending all 8-bits but that's not valid UTF-8 and it caused problems at least with one SDL2 game.

I am now testing a potential solution which uses Diskfont.library to convert to unicode and then doing a manual UTF-8 conversion.

**Comment by walkero-gr** [comment]
@capehill 
I tested those changes yesterday, and they seem to work great. Now I am able to type texts in the alternate keymap. The only thing that seems to be block still are the dead keys. Those are used to add characters with tonality, i.e. those are the same letter but with different tonality ι, ί, ϊ. By not being able to use the dead keys, I always get the first letter.

Is this something we could have fixed?

**Comment by walkero-gr** [comment]
@capehill I compiled the latest SDL 2 today with the above commits and now the "dead keys" seem to work great.
Thank you so much for implementing my requests.

**Comment by capehill** [comment]
Thanks for testing and reporting.

I'm closing this with https://github.com/AmigaPorts/SDL/releases/tag/v2.30.0-rc2-amigaos4
